[project]
dependencies = [
    "cffi>=1.17.1",
    "cryptography>=46.0.3",
    "pythonnet>=3.0.5",
    "pywebview[ssl]>=6.1",
]
description = "一个基于pywebview的本地桌面应用示例"
name = "webview_app"
requires-python = ">=3.10,<3.14"
version = "0.1.0"

[project.scripts]
webview_app = "webview_app.app:main"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
exclude = [
    "src/webview_app/frontend/*.*",
    "src/webview_app/frontend/node_modules/*",
    "src/webview_app/frontend/public/*",
    "src/webview_app/frontend/src/*",
]
include = [
    "src/webview_app/**/*.py",
    "src/webview_app/frontend/deploy/**/*",
]
packages = ["src/webview_app"]

[tool.hatch.build.targets.sdist]
exclude = [
    "src/webview_app/frontend/deploy/**/*",
    "src/webview_app/frontend/node_modules/**/*",
]
include = ["src/webview_app/**/*.py"]

